<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ObdGarage.Core\ObdGarage.Core.csproj" />
    <ProjectReference Include="..\ObdGarage.Obd\ObdGarage.Obd.csproj" />
    <ProjectReference Include="..\ObdGarage.Shared\ObdGarage.Shared.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
