<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\CarApp.Obd\CarApp.Obd.csproj" />
    <ProjectReference Include="..\..\src\CarApp.Core\CarApp.Core.csproj" />
    <ProjectReference Include="..\..\src\CarApp.Application\CarApp.Application.csproj" />
    <ProjectReference Include="..\..\src\CarApp.Data\CarApp.Data.csproj" />
    <ProjectReference Include="..\..\src\CarApp.Shared\CarApp.Shared.csproj" />
    <ProjectReference Include="..\..\src\CarApp.Server\CarApp.Server.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
